GET https://fso-notes-app-ytrms.herokuapp.com/api/persons

###
GET https://fso-notes-app-ytrms.herokuapp.com/api/persons/6

###
DELETE https://fso-notes-app-ytrms.herokuapp.com/api/persons/1

### good request
POST https://fso-notes-app-ytrms.herokuapp.com/api/persons
content-type: application/json

{
    "name": "sample",
    "number": "123342",
    "cursed": true
}

### bad request (no name)
POST https://fso-notes-app-ytrms.herokuapp.com/api/persons
Content-Type: application/json

{
  "number": "123"
}

### bad request (name already exists)
POST https://fso-notes-app-ytrms.herokuapp.com/api/persons
Content-Type: application/json

{
  "name": "Ada Lovelace",
  "number": "123"
}